export GOPATH="$HOME/dev/go"
export PATH=".:$HOME/.local/bin:$HOME/.cargo/bin:$GOPATH/bin:/usr/local/bin:/usr/bin:/usr/sbin:/bin:/sbin"
export EDITOR=nvim
export PAGER="bat -p"
export MOZ_USE_XINPUT2=1
export LC_TIME=en_US.UTF-8
export FZF_DEFAULT_COMMAND="fd --type file"
export BAT_THEME="Nord"
export TERM=xterm-256color
export CARGO_TARGET_DIR=$HOME/.cargo/target_dir
