#! /bin/sh

#### AUTOSTART ####
xset b off
xset r rate 280 45
# setxkbmap us intl -option ctrl:nocaps
setxkbmap -layout us -variant altgr-intl -option nodeadkeys -option ctrl:nocaps
 

#### BSPWM configuration ####
# bspc config border_radius                8
bspc config border_width                  3
bspc config window_gap                    0 
bspc config top_padding                   24 
bspc config bottom_padding                0
bspc config left_padding                  0
bspc config right_padding                 0
bspc config single_monocle                false
bspc config click_to_focus                true
bspc config split_ratio                   0.50
bspc config borderless_monocle            true 
bspc config gapless_monocle               true
bspc config focus_by_distance             true
bspc config focus_follows_pointer         true
bspc config history_aware_focus           true
bspc config remove_disabled_monitors      true
bspc config remove_unplugged_monitors     true
bspc config merge_overlapping_monitors    true
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

#### BSPWM coloring ####
bspc config normal_border_color		      "#555555"
bspc config active_border_color	          "#1f1f1f"
bspc config focused_border_color	      "#c9665e"
bspc config presel_feedback_color	      "#5e81ac"
bspc config urgent_border_color 	      "#dd2727"

bspc rule -a Gimp state=floating follow=on
bspc rule -a Nemo state=floating follow=on
bspc rule -a Blueberry.py state=floating follow=on
bspc rule -a Pavucontrol state=floating follow=on
bspc rule -a Xviewer state=floating follow=on
bspc rule -a Xed state=floating follow=on
bspc rule -a File-roller state=floating follow=on
bspc rule -a Xreader state=floating follow=on
bspc rule -a Pix state=floating follow=on
bspc rule -a Gnome-system-monitor state=floating follow=on
bspc rule -a "cinnamon-settings sound" state=floating follow=on
bspc rule -a "cinnamon-settings mouse" state=floating follow=on
bspc rule -a "Cinnamon-settings.py" state=floating follow=on
bspc rule -a "cinnamon-settings.py" state=floating follow=on
bspc rule -a "cinnamon-settings" state=floating follow=on

bspc monitor -d 1 2


killall -q polybar
MONITOR=$(xrandr --query | grep " connected" | cut -d" " -f1| head -1) polybar -r top &

pgrep -x sxhkd > /dev/null || sxhkd &

killall -q redshift-gtk
redshift-gtk &

killall -q blueberry-tray 
blueberry-tray &

feh --bg-center /usr/share/backgrounds/linuxmint-tina/acaproni_maldives.jpg &

pgrep alacritty || alacritty &
pgrep firefox || firefox &
