local vim = vim
local api = vim.api
local M = {}

local mycolors = {
    mylight = {
        fg = "#232323",
        bg = "#e1e1d0",
        float = "#d8d8c0",
        tabline = "#DBDBC6",
        constant = "#005cc5",
        type = "#689d6a",
        func = "#b16286",
        menu = "#DBDBC6",
        error = "#e8192e",
        warning = "#e27603",
        keyword = "#BD2636",
        string = "#98971a",
        comment = "#6A737D",
        linenr = "#B8B8A6",
        incsearch = "#d65d0e",
        search = "#d79921",
        cursorline = "#D9D9C7",
        diff_delete = "#e8192e",
        diff_add = "#29A146",
        diff_change = "#F5F519",
        diff_text = "#202429",
        statusline_bg = "#5f5853",
        statusline_fg = "#eeeeee",
        statusline_nc = "#b8b1ad",
        visual = "#B8B8A6",
        fzf_bg = "#d79921",
        fzf_fg = "#232323"
    },
    mydark = {
        fg = "#d5c4a1",
        bg = "#1d2021",
        float = "#282828",
        tabline = "#282828",
        constant = "#458588",
        type = "#d5c4a1",
        func = "#8787af",
        menu = "#98971a",
        error = "#ff8566",
        warning = "#f2ba40",
        keyword = "#d79921",
        string = "#689d6a",
        comment = "#585858",
        linenr = "#585858",
        incsearch = "#cc4400",
        search = "#8f650a",
        cursorline = "#282828",
        diff_delete = "#cc2900",
        diff_add = "#98971a",
        diff_change = "#d79921",
        diff_text = "#202429",
        statusline_bg = "#444444",
        statusline_fg = "#eeeeee",
        statusline_nc = "#262626",
        visual = "#444444",
        fzf_bg = "#A1BD2F",
        fzf_fg = "#111111"
    },
    mydark2 = {
        bg = "#d5c4a1",
        fg = "#1d2021",
        float = "#282828",
        tabline = "#282828",
        constant = "#458588",
        type = "#d5c4a1",
        func = "#8787af",
        menu = "#98971a",
        error = "#ff8566",
        warning = "#f2ba40",
        keyword = "#d79921",
        string = "#689d6a",
        comment = "#585858",
        linenr = "#585858",
        incsearch = "#cc4400",
        search = "#8f650a",
        cursorline = "#282828",
        diff_delete = "#cc2900",
        diff_add = "#98971a",
        diff_change = "#d79921",
        diff_text = "#202429",
        statusline_bg = "#444444",
        statusline_fg = "#eeeeee",
        statusline_nc = "#262626",
        visual = "#444444",
        fzf_bg = "#A1BD2F",
        fzf_fg = "#111111"
    }
}

local groups = {
    {name = "Boolean", fg = "constant", bg = "", gui = ""},
    {name = "Character", fg = "constant", bg = "", gui = ""},
    {name = "CocCodeLens", fg = "linenr", bg = "", gui = ""},
    {name = "CocCursorTransparent", fg = "linenr", bg = "", gui = ""},
    {name = "CocErrorSign", fg = "error", bg = "", gui = ""},
    {name = "CocHintSign", fg = "comment", bg = "", gui = ""},
    {name = "CocInfoSign", fg = "comment", bg = "", gui = ""},
    {name = "CocRustChainingHint", fg = "linenr", bg = "", gui = ""},
    {name = "CocWarningSign", fg = "warning", bg = "", gui = ""},
    {name = "Comment", fg = "comment", bg = "", gui = ""},
    {name = "Conditional", fg = "keyword", bg = "", gui = ""},
    {name = "Constant", fg = "constant", bg = "", gui = ""},
    {name = "Cursor", fg = "White", bg = "White", gui = "none"},
    {name = "CursorColumn", fg = "fg", bg = "linenr", gui = ""},
    {name = "CursorLine", fg = "", bg = "cursorline", gui = "none"},
    {name = "CursorLineNr", fg = "fg", bg = "cursorline", gui = "none"},
    {name = "Debug", fg = "error", bg = "", gui = ""},
    {name = "Define", fg = "error", bg = "", gui = "none"},
    {name = "DiffAdd", fg = "fg", bg = "diff_add", gui = ""},
    {name = "DiffChange", fg = "fg", bg = "diff_change", gui = ""},
    {name = "DiffDelete", fg = "fg", bg = "diff_delete", gui = ""},
    {name = "DiffText", fg = "bg", bg = "diff_text", gui = ""},
    {name = "Directory", fg = "func", bg = "", gui = ""},
    {name = "Error", fg = "White", bg = "error", gui = ""},
    {name = "ErrorMsg", fg = "White", bg = "error", gui = ""},
    {name = "Exception", fg = "error", bg = "", gui = ""},
    {name = "FZF", fg = "fzf_fg", bg = "fzf_bg", gui = ""},
    {name = "Float", fg = "constant", bg = "", gui = ""},
    {name = "FoldColumn", fg = "linenr", bg = "bg", gui = ""},
    {name = "Folded", fg = "comment", bg = "float", gui = ""},
    {name = "Identifier", fg = "fg", bg = "", gui = "none"},
    {name = "Ignore", fg = "comment", bg = "", gui = ""},
    {name = "IncSearch", fg = "fg", bg = "incsearch", gui = "bold"},
    {name = "Keyword", fg = "keyword", bg = "", gui = ""},
    {name = "Label", fg = "fg", bg = "", gui = ""},
    {name = "LineNr", fg = "linenr", bg = "bg", gui = ""},
    {name = "LspDiagnosticsError", fg = "error", bg = "", gui = ""},
    {name = "LspDiagnosticsHint", fg = "linenr", bg = "", gui = ""},
    {name = "LspDiagnosticsInformation", fg = "linenr", bg = "", gui = ""},
    {name = "LspDiagnosticsWarning", fg = "warning", bg = "", gui = ""},
    {name = "Macro", fg = "func", bg = "", gui = "none"},
    {name = "MatchParen", fg = "bg", bg = "visual", gui = ""},
    {name = "ModeMsg", fg = "White", bg = "error", gui = ""},
    {name = "MoreMsg", fg = "Black", bg = "warning", gui = ""},
    {name = "NonText", fg = "linenr", bg = "bg", gui = ""},
    {name = "Normal", fg = "fg", bg = "bg", gui = ""},
    {name = "NormalFloat", fg = "fg", bg = "float", gui = ""},
    {name = "Number", fg = "constant", bg = "", gui = ""},
    {name = "Operator", fg = "fg", bg = "", gui = ""},
    {name = "Pmenu", fg = "fg", bg = "tabline", gui = ""},
    {name = "PmenuSbar", fg = "fg", bg = "comment", gui = ""},
    {name = "PmenuSel", fg = "fg", bg = "search", gui = "bold"},
    {name = "PmenuThumb", fg = "fg", bg = "constant", gui = ""},
    {name = "PreCondit", fg = "error", bg = "", gui = "none"},
    {name = "PreProc", fg = "func", bg = "", gui = "none"},
    {name = "Question", fg = "White", bg = "error", gui = ""},
    {name = "Repeat", fg = "keyword", bg = "", gui = ""},
    {name = "Search", fg = "fg", bg = "search", gui = "bold"},
    {name = "SignColumn", fg = "fg", bg = "bg", gui = ""},
    {name = "Special", fg = "fg", bg = "", gui = ""},
    {name = "SpecialChar", fg = "constant", bg = "", gui = ""},
    {name = "SpecialComment", fg = "constant", bg = "bg", gui = ""},
    {name = "SpecialKey", fg = "linenr", bg = "bg", gui = ""},
    {name = "SpellBad", fg = "fg", bg = "bg", gui = "undercurl"},
    {name = "SpellCap", fg = "error", bg = "bg", gui = "undercurl"},
    {name = "SpellLocal", fg = "fg", bg = "", gui = "undercurl"},
    {name = "SpellRare", fg = "fg", bg = "", gui = "undercurl"},
    {name = "Statement", fg = "fg", bg = "", gui = ""},
    {name = "StatusLine", fg = "statusline_fg", bg = "statusline_bg", gui = "none"},
    {name = "StatusLineNC", fg = "comment", bg = "statusline_nc", gui = "none"},
    {name = "StorageClass", fg = "constant", bg = "", gui = ""},
    {name = "String", fg = "string", bg = "", gui = ""},
    {name = "Structure", fg = "constant", bg = "", gui = ""},
    {name = "TSAnnotation", fg = "fg", bg = "", gui = ""},
    {name = "TSAttribute", fg = "fg", bg = "", gui = ""},
    {name = "TSBoolean", fg = "fg", bg = "", gui = ""},
    {name = "TSCharacter", fg = "fg", bg = "", gui = ""},
    {name = "TSConditional", fg = "keyword", bg = "", gui = ""},
    {name = "TSConstBuiltin", fg = "fg", bg = "", gui = ""},
    {name = "TSConstMacro", fg = "func", bg = "", gui = ""},
    {name = "TSConstant", fg = "constant", bg = "", gui = ""},
    {name = "TSConstructor", fg = "fg", bg = "", gui = ""},
    {name = "TSEmphasis", fg = "fg", bg = "", gui = ""},
    {name = "TSError", fg = "fg", bg = "error", gui = ""},
    {name = "TSException", fg = "fg", bg = "", gui = ""},
    {name = "TSField", fg = "fg", bg = "", gui = ""},
    {name = "TSFloat", fg = "fg", bg = "float", gui = ""},
    {name = "TSFuncBuiltin", fg = "func", bg = "", gui = ""},
    {name = "TSFuncMacro", fg = "func", bg = "", gui = ""},
    {name = "TSFunction", fg = "func", bg = "", gui = ""},
    {name = "TSInclude", fg = "keyword", bg = "", gui = ""},
    {name = "TSKeyword", fg = "keyword", bg = "", gui = ""},
    {name = "TSKeywordFunction", fg = "keyword", bg = "", gui = ""},
    {name = "TSKeywordOperator", fg = "keyword", bg = "", gui = ""},
    {name = "TSLabel", fg = "fg", bg = "", gui = ""},
    {name = "TSLiteral", fg = "fg", bg = "", gui = ""},
    {name = "TSMethod", fg = "func", bg = "", gui = ""},
    {name = "TSNamespace", fg = "fg", bg = "", gui = ""},
    {name = "TSNone", fg = "keyword", bg = "", gui = ""},
    {name = "TSNumber", fg = "number", bg = "", gui = ""},
    {name = "TSOperator", fg = "fg", bg = "", gui = ""},
    {name = "TSParameter", fg = "fg", bg = "", gui = ""},
    {name = "TSParameterReference", fg = "fg", bg = "", gui = ""},
    {name = "TSProperty", fg = "fg", bg = "", gui = ""},
    {name = "TSPunctBracket", fg = "fg", bg = "", gui = ""},
    {name = "TSPunctDelimiter", fg = "fg", bg = "", gui = ""},
    {name = "TSPunctSpecial", fg = "fg", bg = "", gui = ""},
    {name = "TSRepeat", fg = "keyword", bg = "", gui = ""},
    {name = "TSString", fg = "string", bg = "", gui = ""},
    {name = "TSStringEscape", fg = "fg", bg = "", gui = ""},
    {name = "TSStringRegex", fg = "fg", bg = "", gui = ""},
    {name = "TSStrong", fg = "fg", bg = "", gui = "bold"},
    {name = "TSTag", fg = "fg", bg = "", gui = ""},
    {name = "TSTagDelimiter", fg = "fg", bg = "", gui = ""},
    {name = "TSText", fg = "fg", bg = "", gui = ""},
    {name = "TSTitle", fg = "fg", bg = "", gui = ""},
    {name = "TSType", fg = "type", bg = "", gui = ""},
    {name = "TSTypeBuiltin", fg = "type", bg = "", gui = ""},
    {name = "TSURI", fg = "func", bg = "", gui = "underline"},
    {name = "TSUnderline", fg = "fg", bg = "", gui = "underline"},
    {name = "TSVariable", fg = "fg", bg = "", gui = ""},
    {name = "TSVariableBuiltin", fg = "fg", bg = "", gui = ""},
    {name = "TabLine", fg = "comment", bg = "tabline", gui = "none"},
    {name = "TabLineFill", fg = "comment", bg = "tabline", gui = "none"},
    {name = "TabLineSel", fg = "fg", bg = "bg", gui = "bold"},
    {name = "Tag", fg = "fg", bg = "", gui = "bold"},
    {name = "Title", fg = "constant", bg = "", gui = ""},
    {name = "Todo", fg = "constant", bg = "bg", gui = ""},
    {name = "Type", fg = "fg", bg = "", gui = "none"},
    {name = "Typedef", fg = "constant", bg = "", gui = ""},
    {name = "Underlined", fg = "fg", bg = "", gui = "underline"},
    {name = "VertSplit", fg = "statusline_bg", bg = "bg", gui = "none"},
    {name = "Visual", bg = "visual", gui = ""},
    {name = "VisualNOS", fg = "bg", bg = "visual", gui = ""},
    {name = "WarningMsg", fg = "White", bg = "warning", gui = ""},
    {name = "cssPseudoClassId", fg = "func", bg = "", gui = ""},
    {name = "cssTagName", fg = "keyword", bg = "", gui = ""},
    {name = "cssUnitDecorators", fg = "error", bg = "", gui = ""},
    {name = "easymotiontargetdefault", fg = "error", bg = "", gui = ""},
    {name = "function", fg = "func", bg = "", gui = "none"},
    {name = "goBlock", fg = "fg", bg = "", gui = ""},
    {name = "goField", fg = "fg", bg = "", gui = ""},
    {name = "goFunctionCall", fg = "constant", bg = "", gui = ""},
    {name = "goMethodCall", fg = "constant", bg = "", gui = ""},
    {name = "goOperator", fg = "fg", bg = "", gui = ""},
    {name = "goType", fg = "error", bg = "", gui = ""},
    {name = "goTypeName", fg = "fg", bg = "", gui = ""},
    {name = "goTypeName", fg = "fg", bg = "", gui = ""},
    {name = "htmlH1", fg = "keyword", bg = "", gui = ""},
    {name = "htmlH2", fg = "constant", bg = "", gui = ""},
    {name = "htmlH3", fg = "constant", bg = "", gui = ""},
    {name = "htmlH4", fg = "constant", bg = "", gui = ""},
    {name = "htmlH5", fg = "fg", bg = "", gui = ""},
    {name = "htmlH6", fg = "fg", bg = "", gui = ""},
    {name = "htmltagname", fg = "func", bg = "", gui = ""},
    {name = "jsClassDefinition", fg = "func", bg = "", gui = ""},
    {name = "jsClassFuncName", fg = "func", bg = "", gui = ""},
    {name = "jsDocType", fg = "func", bg = "", gui = ""},
    {name = "jsExceptions", fg = "func", bg = "", gui = ""},
    {name = "jsFrom", fg = "error", bg = "", gui = ""},
    {name = "jsFuncCall", fg = "func", bg = "", gui = ""},
    {name = "jsGlobalNodeObjects", fg = "constant", bg = "", gui = ""},
    {name = "jsGlobalObjects", fg = "func", bg = "", gui = ""},
    {name = "jsImport", fg = "error", bg = "", gui = ""},
    {name = "jsModuleAs", fg = "error", bg = "", gui = ""},
    {name = "jsStorageClass", fg = "error", bg = "", gui = ""},
    {name = "jsThis", fg = "constant", bg = "", gui = ""},
    {name = "jsThis", fg = "constant", bg = "", gui = ""},
    {name = "jsVariableDef", fg = "fg", bg = "", gui = ""},
    {name = "jsonBraces", fg = "fg", bg = "", gui = ""},
    {name = "jsonKeyword", fg = "string", bg = "", gui = ""},
    {name = "luatreerootfolder", fg = "keyword", bg = "", gui = ""},
    {name = "markdownH1", fg = "fg", bg = "search", gui = ""},
    {name = "markdownH2", fg = "constant", bg = "", gui = ""},
    {name = "markdownH3", fg = "constant", bg = "", gui = ""},
    {name = "markdownH4", fg = "constant", bg = "", gui = ""},
    {name = "mkdHeading", fg = "keyword", bg = "", gui = ""},
    {name = "mkdLineBreak", fg = "fg", bg = "", gui = ""},
    {name = "mkdURL", fg = "constant", bg = "", gui = ""},
    {name = "scalaExternal", fg = "keyword", bg = "", gui = ""},
    {name = "scalatypeannotation", fg = "fg", bg = "", gui = ""},
    -- {name = "typescriptparens", fg = "fg", bg = "", gui = ""},
    {name = "vimCommand", fg = "keyword", bg = "", gui = ""},
    {name = "vimIsCommand", fg = "constant", bg = "", gui = ""},
    {name = "vimLet", fg = "keyword", bg = "", gui = ""},
    {name = "vimNotFunc", fg = "keyword", bg = "", gui = ""},
    {name = "vimOption", fg = "constant", bg = "", gui = ""},
    {name = "vimParenSep", fg = "fg", bg = "", gui = ""},
    {name = "vimSet", fg = "constant", bg = "", gui = ""},
    {name = "vimUserFunc", fg = "func", bg = "", gui = ""},
    {name = "yamlKey", fg = "keyword", bg = "", gui = ""}
}

function M.MyColors(color_name)
    local name = color_name or "mydark"
    -- vim.g.colors_name = name
    --
    api.nvim_exec([[ 
        hi clear
        syntax reset
        set background=dark
        ]], "")

    local color = mycolors[name]
    for _, group in pairs(groups) do
        local s = "silent hi! " .. group["name"]

        local fg = color[group["fg"]]
        if fg then
            s = s .. " guifg=" .. fg
        end

        local bg = color[group["bg"]]
        if bg then
            s = s .. " guibg=" .. bg
        end

        local gui = color[group["gui"]]
        if gui then
            s = s .. " gui=" .. gui
        else
            s = s .. " gui=none"
        end

        vim.cmd(s)
    end
end

api.nvim_exec([[ command! -nargs=1 MySetColor lua require'colors'.MyColors(<q-args>) ]], "")
api.nvim_exec(
    [[ command! -nargs=0 MyColor call fzf#run({"source": ['mylight', 'mydark','mydark2'], "options": '--reverse',"sink": "MySetColor"}) ]],
    ""
)
M.MyColors()

return M
