local Color, c, Group, g, s = require('colorbuddy').setup()

vim.g.colors_name = 'mycolor'

-- COLORS
if vim.o.background == 'dark' then
    Color.new('black',         '#000000')
    Color.new('white',         '#ffffff')
    Color.new('darkred',       '#FA8072') -- salmon
    Color.new('darkorange',    '#FF8C00')
    Color.new('goldenrod',     '#DAA520')
    Color.new('darkgreen',     '#90EE90') -- lightgreen
    Color.new('darkcyan',      '#48D1CC') -- mediumturquoise
    Color.new('navy',          '#4682B4') -- steelblue
    Color.new('steelblue',     '#4682B4')
    Color.new('darkviolet',    '#9400D3')
    Color.new('darkgray',      '#A9A9A9')
    Color.new('darkolivegreen','#556B2F')
    Color.new('sienna',        '#A0522D')
    Group.new('Normal'         ,c.white:dark(0.15), c.black:light(0.18))
else
    Color.new('black',         '#000000')
    Color.new('white',         '#ffffff')
    Color.new('darkred',       '#8b0000')
    Color.new('darkorange',    '#FF8C00')
    Color.new('goldenrod',     '#DAA520')
    Color.new('darkgreen',     '#006400')
    Color.new('darkcyan',      '#008b8b')
    Color.new('navy',          '#000080')
    Color.new('steelblue',     '#4682B4')
    Color.new('darkviolet',    '#9400D3')
    Color.new('darkolivegreen','#556B2F')
    Color.new('sienna',        '#A0522D')
    Group.new('Normal'        ,c.black, c.white:dark(0.03))
end

-- SPECS
Group.new('Comment'       ,c.darkgray, nil, s.italic)
Group.new('Constant'      ,nil,nil,nil)
Group.new('Number'        ,c.darkcyan,nil,s.bold)
Group.new('String'        ,c.darkgreen,nil,nil)
Group.new('Character'     ,g.String,g.String,g.String)
Group.new('Identifier'    ,nil,nil,nil)
Group.new('Function'      ,nil,nil,s.bold)
Group.new('Statement'     ,nil,nil,s.bold)
Group.new('Keyword'       ,nil,nil,s.bold)
Group.new('PreProc'       ,g.Normal.fg:light(0.5),nil,nil)
Group.new('Macro'         ,g.Normal.fg:light(0.5),nil,nil)
Group.new('Type'          ,nil,nil,nil)
Group.new('Special'       ,nil,nil,nil)
Group.new('SpecialChar'   ,c.darkorange, nil, s.bold)
Group.new('Underlined'    ,nil, nil, s.underline)
Group.new('Ignore'        ,g.Normal.bg, c.darkred, nil)
Group.new('Error'         ,c.darkred, nil,  s.bold+s.reverse)
Group.new('Todo'          ,g.Normal.bg, g.Comment.fg, s.bold)
Group.new('Delimiter'     ,nil,nil,nil)
Group.new('StorageClass'  ,nil,nil,nil)
Group.new('Operator'      ,nil,nil,s.bold)
Group.new('Include'       ,nil,nil,nil)
Group.new('helpExample'   ,c.navy,nil,nil)
Group.new('SpecialKey'    ,g.Normal.fg:light(0.1), nil, s.bold)
Group.new('NonText'       ,g.Normal.bg:light(0.2), nil, nil)
Group.new('Conceal'       ,g.Normal.fg:light(0.2), g.Normal.bg:dark(0.1), s.bold)
Group.new('MatchParen'    ,c.darkorange,nil, s.bold + s.underline)
Group.new('ModeMsg'       ,nil,nil,s.bold)
Group.new('MoreMsg'       ,c.darkcyan,nil, s.bold)
Group.new('WarningMsg'    ,c.darkorange,nil, s.bold)
Group.new('ErrorMsg'      ,c.darkred,nil, s.bold)
Group.new('Question'      ,g.MoreMsg, g.MoreMsg, g.MoreMsg)
Group.new('Title'         ,c.navy, nil, s.bold)
Group.new('IncSearch'     ,c.white,c.darkgreen, s.bold )
Group.new('Search'        ,c.white,c.darkorange, s.bold)
Group.new('WildMenu'      ,c.darkorange, g.Normal.bg, s.reverse)
Group.new('Directory'     ,g.Title,g.Title,g.Title)
Group.new('DiffAdd'       ,c.darkgreen,g.Normal.bg:light(0.1), s.bold)
Group.new('DiffChange'    ,c.goldenrod,g.Normal.bg:light(0.1), s.bold, c.goldenrod)
Group.new('DiffDelete'    ,c.darkred, g.Normal.bg:light(0.1), s.bold)
Group.new('DiffText'      ,c.navy, g.Normal.bg:light(0.1), s.bold+s.undercurl, c.navy)
Group.new('SpellBad'      ,nil,nil,s.undercurl, c.darkred)
Group.new('SpellCap'      ,nil,nil,s.undercurl, c.navy)
Group.new('SpellRare'     ,nil,nil,s.undercurl, c.darkviolet)
Group.new('SpellLocal'    ,nil,nil,s.undercurl, c.darkcyan)
Group.new('Pmenu'         ,g.Normal.fg, g.Normal.bg:dark(0.05))
Group.new('PmenuSel'      ,g.Normal.bg,g.Normal.fg,s.bold)
Group.new('PmenuSbar'     ,g.Normal.bg:light(0.5))
Group.new('PmenuThumb'    ,nil,g.Normal.fg)
Group.new('LineNr'        ,c.darkgray,nil,s.italic)
Group.new('CursorLine'    ,nil,g.Normal.bg:dark(0.03))
Group.new('CursorLineNr'  ,g.Normal.fg,g.Cursorline.bg,s.bold)
Group.new('CursorColumn'  ,nil,g.Normal.bg:dark(0.1))
Group.new('VertSplit'     ,g.Normal.bg:dark(0.2))
Group.new('SignColumn'    ,nil,nil,nil)
Group.new('Folded'        ,c.darkcyan, g.Normal.bg:dark(0.05),s.bold)
Group.new('Cursor'        ,c.white, c.steelblue,s.bold)
Group.new('lCursor'       ,c.white, c.darkviolet,s.bold)

-- Group.new('GColumn'   ,'bg=darkorange')
-- Group.new('FoldColumn'    ,'fg=bg1 bg=bg3')
--
--
-- -- PLUGINS
-- Group.new('lualine_c_normal'                  ,g.Normal.bg, c.steelblue)
Group.new('GitSignsAdd'                       ,c.darkgreen, nil, s.bold)
Group.new('GitSignsChange'                    ,c.goldenrod,nil, s.bold)
Group.new('GitSignsDelete'                    ,c.darkred,nil, s.bold)
Group.new('GitSignsSelectionCaret'            ,c.black)
Group.new('TelescopeNormal'                   ,g.Normal.fg:light(0.35))
Group.new('TelescopeSelection'                ,c.darkred,nil, s.bold + s.underline)
Group.new('TelescopeMatching'                 ,g.TelescopeSelection.fg,nil, s.bold)
Group.new('TelescopeBorder'                   ,g.VertSplit,g.VertSplit)
Group.new('yamlTSField'                       ,g.Normal.fg,nil,s.bold)
Group.new('yamlBlockMappingKey'               ,c.navy)
Group.new('tomlTSTypeBuiltin'                 ,c.navy)
Group.new('tomlTSProperty'                    ,g.Normal.fg:light(0.1))
Group.new('MarkdownCode'                      ,c.darkviolet)
Group.new('MarkdownLinkText'                  ,c.darkcyan)
Group.new('MarkdownUrl'                       ,nil, nil, s.italic)
Group.new('MarkdownListMarker'                ,c.darkred)
Group.new('MarkdownH1'                        ,g.Normal.fg,nil, s.bold)
Group.new('MarkdownH2'                        ,g.MarkdownH1.fg:light(0.3),nil,s.bold+s.italic)
Group.new('MarkdownH3'                        ,c.darkcyan,nil,s.italic+s.bold)
Group.new('MarkdownH1Delimiter'               ,g.MarkdownH1.fg,nil,s.bold)
Group.new('MarkdownH2Delimiter'               ,g.MarkdownH2.fg,nil,s.italic)
Group.new('MarkdownH3Delimiter'               ,g.MarkdownH3.fg,nil,s.italic)
Group.new('HopNextKey'                        ,c.darkred,nil, s.bold + s.underline)
Group.new('HopNextKey1'                       ,c.darkred,nil, s.bold + s.underline)
Group.new('BufferCurrent'                     ,g.Normal.fg,nil,s.bold)
Group.new('BufferCurrentIndex'                ,g.Normal.fg,nil,s.bold)
Group.new('BufferCurrentMod'                  ,g.Normal.fg,nil,s.bold)
Group.new('BufferCurrentSign'                 ,g.Normal.fg,nil,s.bold)
Group.new('BufferTabpageFill'                 ,nil,g.Normal.bg:light(0.3))
Group.new('BufferInactive'                    ,nil,g.Normal.bg:light(0.2))
Group.new('BufferInactiveIndex'               ,nil,g.Normal.bg:light(0.2))
Group.new('BufferInactiveSign'                ,nil,g.Normal.bg:light(0.2))
Group.new('TSProperty'                        ,g.Normal.fg:light(0.1))
Group.new('TSTagDelimiter'                    ,g.Normal.fg:light(0.1))
Group.new('TSInclude'                         ,nil,nil,s.bold)
Group.new('TSRepeat'                          ,nil,nil,s.bold)
Group.new('TSNamespace'                       ,nil,nil,nil)
Group.new('TSVariable'                        ,nil,nil,nil)
Group.new('TSPunctDelimiter'                  ,c.darkgray)
Group.new('TSPunctSpecial'                    ,nil,nil,s.bold)
Group.new('TSAnnotation'                      ,nil,nil,s.bold)
Group.new('TSAttribute'                       ,nil,nil,s.bold)
Group.new('TSConstMacro'                      ,c.darkcyan,nil,s.bold)
Group.new('TSDefinitionUsage'                 ,c.darkorange,g.Normal.bg:dark(0.05),s.bold)
Group.new('TSFuncMacro'                       ,g.Normal.fg)
Group.new('RustTSKeywordOperator'             ,nil, nil, s.bold)
Group.new('RustTSKeywordFunction'             ,nil, nil, s.bold)
Group.new('NeogitStagedchanges'               ,c.darkred,nil,s.bold)
Group.new('NeogitUnstagedchanges'             ,c.goldenrod,nil,s.bold)
Group.new('NeogitUntrackedfiles'              ,c.darkcyan,nil,s.bold)
Group.new('NeogitHunkHeader'                  ,c.black,nil,s.bold)
Group.new('LspDiagnosticsDefaultError'        ,c.darkred,nil,s.bold)
Group.new('LspDiagnosticsDefaultWarning'      ,c.darkorange,nil,s.bold)
Group.new('LspDiagnosticsDefaultInfo'         ,c.darkcyan,nil,s.bold)
Group.new('LspDiagnosticsDefaultHint'         ,c.darkcyan,nil,s.bold)
Group.new('LspDiagnosticsUnderlineError'      ,nil,nil,s.undercurl,c.darkred)
Group.new('LspDiagnosticsUnderlineWarning'   ,nil,nil,s.undercurl,c.goldenrod)
Group.new('LspDiagnosticsUnderlineInformation',nil,nil,s.undercurl,c.darkcyan)
Group.new('LspDiagnosticsUnderlineHint'       ,nil,nil,s.undercurl,c.darkcyan)
Group.new('FocusedSymbol'                     ,nil,c.goldenrod)
Group.new('NvimTreeNormal'                    ,nil,g.Normal.bg:dark(0.05))
